name: Deploy Firebase (Hosting + Functions)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ruvia-b758a
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci

      - name: Build web
        run: npm run build:web

      - name: Install backend dependencies
        run: npm ci --prefix backend

      - name: Build backend (TypeScript)
        run: npm run build --prefix backend

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Authenticate with service account
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT" > "$RUNNER_TEMP/gcp-key.json"
          echo "GOOGLE_APPLICATION_CREDENTIALS=$RUNNER_TEMP/gcp-key.json" >> $GITHUB_ENV

      - name: Write backend env file
        env:
          FAL_KEY: ${{ secrets.FAL_KEY }}
          ANDROID_PACKAGE_NAME: ${{ secrets.ANDROID_PACKAGE_NAME }}
        run: |
          mkdir -p backend
          {
            echo "FAL_KEY=${FAL_KEY}"
            echo "ANDROID_PACKAGE_NAME=${ANDROID_PACKAGE_NAME}"
          } > backend/.env

      - name: Deploy Hosting + Functions
        run: firebase deploy --only hosting,functions --project $PROJECT_ID
